### ISSUE TITLE
Query on CC0 license

### ISSUE THREAD

**Issue by saurabhdhiman** [djnavarro/series-water-colours#1]
@djnavarro thanks for sharing your art for such a good cause ! 
And sorry, its not really an issue but a query that I wasn't sure where to ask.
The readme says that the images in this repository are released under the CC0 license. Does that hold for the source files shared on this repo as well ?
I love this series and I am keen to explore this method on some pictures I have taken. But wanted to make sure if you are allowing that with this release ?

**Comment by djnavarro** [comment]
Ah, right. I've been thinking a little about the licence for the code. The reason for hesitating is that I don't think CC licences are generally a good fit for code. What I'm going to do, however, is place the code under an MIT licence, which would allow you to do that!

**Comment by djnavarro** [comment]
Thanks for reminding me to address this!

**Comment by saurabhdhiman** [comment]
Great, thanks for placing it under MIT :)
